#!/usr/bin/env bash

setup_enviroment() {
    validate_xcode_version
    install_system_basics
    install_brew_dependencies
    install_carthage_dependencies
    open_project
}

validate_xcode_version() {
    echo "Validating Xcode version..."
    xcode_version=$(xcodebuild -version|grep -e '\d\+\.\d\+' -o)
    minimum_version=11.0
    if (( $(echo "$xcode_version < $minimum_version" | bc -l) )); then
        echo -e "\033[31mYou must have/select Xcode $minimum_version+"
        echo "Try: sudo xcode-select -s /Applications/Xcode[Version].app"
        echo "Or download and install Xcode above $minimum_version"
        exit 1
    fi
}

install_system_basics() {
    echo "Setup system basics..."
    if ! type "brew" &> /dev/null; then
        echo "Installing brew..."
        eval '/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)'
    fi
}

install_brew_dependencies() {
    echo "Setup brew packages..."
    brew_dependencies=(carthage swiftlint imagemagick sourcery)

    for brew_dependency in "${brew_dependencies[@]}"; do
        if ! brew ls --versions ${brew_dependency} > /dev/null; then
            echo "Installing $brew_dependency..."
            brew install $brew_dependency
        fi
    done
}

install_carthage_dependencies() {
    echo "Setup carthage..."
    if [ -f "Cartfile" ]; then
        carthage bootstrap --platform iOS
    fi
}

open_project() {
    while true; do
        read -p "Open project on Xcode? " yn
        case $yn in
            [Yy]* ) xed .; break;;
            * ) exit;;
        esac
    done
}

setup_enviroment