#!/usr/bin/env bash

size=$1
path_origin=$(realpath $2)
path_destiny=$(realpath $3)
path_current=$PWD

mkdir -p $path_destiny
cd $path_origin

mogrify -path $path_destiny \
    -resize $size^ \
    -gravity center \
    -extent $size^ \
    *

cd $path_current
