#!/usr/bin/env bash

setup_enviroment() {
    validate_xcode_version
    install_system_basics
    install_brew_dependencies
    install_carthage_dependencies
}

install_system_basics() {
    if ! type "brew" &> /dev/null; then
        echo "Installing brew..."
        eval '/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)'
    fi
}

install_brew_dependencies() {
    brew_dependencies=(carthage swiftlint)
    for brew_dependency in "${brew_dependencies[@]}"; do
        echo "Installing $brew_dependency..."
        brew install $brew_dependency
    done
}

install_carthage_dependencies() {
    carthage bootstrap --platform iOS
}

validate_xcode_version() {
    xcode_version=$(xcodebuild -version)
    if ! [[ $xcode_version = *"9.3"* ]]; then
        echo -e "\033[31mYou must have/select Xcode 9.3.0" >&2
        exit 1
    fi
}

setup_enviroment
