import Foundation

let pineapple = Food(keyName: "PINEAPPLE", months: [1, 3, 9, 10, 11, 12])
let starFruit = Food(keyName: "STAR_FRUIT", months: [1, 2, 6, 7, 8])
let greenCoconut = Food(keyName: "GREEN_COCONUT", months: [1, 2, 3, 10, 11, 12])
let fig = Food(keyName: "FIG", months: [1, 2, 3, 12])
let raspberry = Food(keyName: "RASPBERRY", months: [1, 11, 12])
let custardApple = Food(keyName: "CUSTARD_APPLE", months: [1, 2, 3])
let orangePear = Food(keyName: "ORANGE_PEAR", months: [1, 8, 9, 10, 11, 12])
let papaya = Food(keyName: "PAPAYA", months: [1, 3, 4, 8, 10, 11])
let passionFruit = Food(keyName: "PASSION_FRUIT", months: [1, 11, 12])
let watermelon = Food(keyName: "WATERMELON", months: [1, 11, 12])
let nectarine = Food(keyName: "NECTARINE", months: [1, 3, 11, 12])
let grape = Food(keyName: "GRAPE", months: [1, 2, 3, 4, 5, 10, 11, 12])
let lettuce = Food(keyName: "LETTUCE", months: [1, 3, 4])
let chive = Food(keyName: "CHIVE", months: [1, 10, 11, 12])
let cabbage = Food(keyName: "CABBAGE", months: [1, 7, 8, 9, 10])
let parsley = Food(keyName: "PARSLEY", months: [1, 3, 7, 12])
let pumpkin = Food(keyName: "PUMPKIN", months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
let zucchini = Food(keyName: "ZUCCHINI", months: [1, 3, 5, 8])
let beet = Food(keyName: "BEET", months: [1, 3, 4, 5, 10, 11, 12])
let cucumber = Food(keyName: "CUCUMBER", months: [1, 2, 3, 4, 7, 10, 11, 12])
let pepper = Food(keyName: "PEPPER", months: [1, 2, 8, 9, 10, 11, 12])
let okra = Food(keyName: "OKRA", months: [1, 2, 3])
let tomato = Food(keyName: "TOMATO", months: [1, 2, 3, 4, 10, 11, 12])
let avocado = Food(keyName: "AVOCADO", months: [2, 3, 4, 5])
let plum = Food(keyName: "PLUM", months: [2, 3, 4, 12])
let guava = Food(keyName: "GUAVA", months: [2, 3])
let jaca = Food(keyName: "JACA", months: [2, 3, 4, 5, 6])
let apple = Food(keyName: "APPLE", months: [2, 3, 4, 5, 8, 9, 10, 11, 12])
let pear = Food(keyName: "PEAR", months: [2, 3, 4, 5])
let peach = Food(keyName: "PEACH", months: [2, 3, 11, 12])
let seriguela = Food(keyName: "SERIGUELA", months: [2, 3])
let escarole = Food(keyName: "ESCAROLE", months: [2, 3, 4, 8])
let mint = Food(keyName: "MINT", months: [2, 10, 12])
let ginger = Food(keyName: "GINGER", months: [2, 3, 4, 6])
let greenCorn = Food(keyName: "GREEN_CORN", months: [2, 3, 6, 7])
let bananaApple = Food(keyName: "BANANA_APPLE", months: [3, 4, 5])
let bananaNanica = Food(keyName: "BANANA_NANICA", months: [3, 8, 9, 10, 11])
let lemon = Food(keyName: "LEMON", months: [3, 12])
let mangosteen = Food(keyName: "MANGOSTEEN", months: [3, 6])
let tangerine = Food(keyName: "TANGERINE", months: [3, 4, 5, 6, 7, 8, 9, 10, 11])
let chard = Food(keyName: "CHARD", months: [3])
let leek = Food(keyName: "LEEK", months: [3, 4, 5, 6, 7, 8, 9, 10, 11])
let coriander = Food(keyName: "CORIANDER", months: [3, 7, 8, 10])
let endive = Food(keyName: "ENDIVE", months: [3, 11, 12])
let arugula = Food(keyName: "ARUGULA", months: [3, 8, 12])
let eggplant = Food(keyName: "EGGPLANT", months: [3, 4, 5, 6, 10, 11])
let cara = Food(keyName: "CARA", months: [3, 4, 5, 6, 7, 8, 9])
let chuchu = Food(keyName: "CHUCHU", months: [3, 4, 5])
let yam = Food(keyName: "YAM", months: [3, 4, 5, 6, 7, 8, 9, 10, 11])
let jelly = Food(keyName: "JELLY", months: [3])
let turnip = Food(keyName: "TURNIP", months: [3, 4, 5, 7, 8, 11])
let khaki = Food(keyName: "KHAKI", months: [4, 5])
let cider = Food(keyName: "CIDER", months: [4])
let kiwi = Food(keyName: "KIWI", months: [4, 5, 6, 7, 8, 12])
let willReach = Food(keyName: "WILL_REACH", months: [4, 5, 6, 9, 10, 11, 12])
let catalan = Food(keyName: "CATALAN", months: [4, 10])
let fennel = Food(keyName: "FENNEL", months: [5, 6, 7, 8, 9, 10, 11, 12])
let bay = Food(keyName: "BAY", months: [5, 9])
let sweetPotato = Food(keyName: "SWEET_POTATO", months: [5, 6, 7, 10])
let carrot = Food(keyName: "CARROT", months: [5, 6, 7, 8, 9, 10, 11, 12])
let manioc = Food(keyName: "MANIOC", months: [5, 6, 7, 8])
let littleManioc = Food(keyName: "LITTLE_MANIOC", months: [5, 6, 7, 8])
let radish = Food(keyName: "RADISH", months: [5, 7, 8, 9, 10])
let quince = Food(keyName: "QUINCE", months: [6])
let cress = Food(keyName: "CRESS", months: [6, 7, 8])
let broccoli = Food(keyName: "BROCCOLI", months: [6, 8, 9, 10, 11])
let pea = Food(keyName: "PEA", months: [6, 7, 8, 9, 10])
let palmHeart = Food(keyName: "PALM_HEART", months: [6, 7])
let chicory = Food(keyName: "CHICORY", months: [7, 8, 9, 10])
let spinach = Food(keyName: "SPINACH", months: [7, 8, 9, 10, 11])
let mustard = Food(keyName: "MUSTARD", months: [7, 8, 10])
let celery = Food(keyName: "CELERY", months: [7, 12])
let mushroom = Food(keyName: "MUSHROOM", months: [7, 9, 10, 12])
let cashew = Food(keyName: "CASHEW", months: [8, 9, 10, 11])
let lime = Food(keyName: "LIME", months: [8, 10])
let strawberry = Food(keyName: "STRAWBERRY", months: [8])
let cauliflower = Food(keyName: "CAULIFLOWER", months: [8, 9, 10])
let fava = Food(keyName: "FAVA", months: [8, 9, 10])
let jaboticaba = Food(keyName: "JABOTICABA", months: [9, 10])
let medlar = Food(keyName: "MEDLAR", months: [9, 10])
let tamarind = Food(keyName: "TAMARIND", months: [9])
let oregano = Food(keyName: "OREGANO", months: [9, 10, 12])
let acerola = Food(keyName: "ACEROLA", months: [10, 11])
let silverBanana = Food(keyName: "SILVER_BANANA", months: [10, 11, 12])
let mango = Food(keyName: "MANGO", months: [10, 11, 12])
let grapeLeaf = Food(keyName: "GRAPE_LEAF", months: [10, 11, 12])
let artichoke = Food(keyName: "ARTICHOKE", months: [10])
let asparagus = Food(keyName: "ASPARAGUS", months: [10, 11])
let khakiTomato = Food(keyName: "KHAKI_TOMATO", months: [10])
let melon = Food(keyName: "MELON", months: [11, 12])
let maxixe = Food(keyName: "MAXIXE", months: [11])
let cherry = Food(keyName: "CHERRY", months: [12])
let damascus = Food(keyName: "DAMASCUS", months: [12])
let graviola = Food(keyName: "GRAVIOLA", months: [12])
let litchi = Food(keyName: "LITCHI", months: [12])
let pomegranate = Food(keyName: "POMEGRANATE", months: [12])
let podNoodles = Food(keyName: "POD_NOODLES", months: [12])

let allFruits = [
    pineapple, starFruit, greenCoconut, fig, raspberry, custardApple, orangePear, papaya, passionFruit, watermelon,
    nectarine, grape, lettuce, chive, cabbage, parsley, pumpkin, zucchini, beet, cucumber, pepper, okra, tomato,
    avocado, plum, guava, jaca, apple, pear, peach, seriguela, escarole, mint, ginger, greenCorn, bananaApple,
    bananaNanica, lemon, mangosteen, tangerine, chard, leek, coriander, endive, arugula, eggplant, cara, chuchu, yam,
    jelly, turnip, khaki, cider, kiwi, willReach, catalan, fennel, bay, sweetPotato, carrot, manioc, littleManioc,
    radish, quince, cress, broccoli, pea, palmHeart, chicory, spinach, mustard, celery, mushroom, cashew, lime,
    strawberry, cauliflower, fava, jaboticaba, medlar, tamarind, oregano, acerola, silverBanana, mango, grapeLeaf,
    artichoke, asparagus, khakiTomato, melon, maxixe, cherry, damascus, graviola, litchi, pomegranate, podNoodles]
