struct DataSource {
    private static let pineapple = Food(keyName: "PINEAPPLE", months: [1, 3, 9, 10, 11, 12])
    private static let starFruit = Food(keyName: "STAR_FRUIT", months: [1, 2, 6, 7, 8])
    private static let greenCoconut = Food(keyName: "GREEN_COCONUT", months: [1, 2, 3, 10, 11, 12])
    private static let fig = Food(keyName: "FIG", months: [1, 2, 3, 12])
    private static let raspberry = Food(keyName: "RASPBERRY", months: [1, 11, 12])
    private static let custardApple = Food(keyName: "CUSTARD_APPLE", months: [1, 2, 3])
    private static let orangePear = Food(keyName: "ORANGE_PEAR", months: [1, 8, 9, 10, 11, 12])
    private static let papaya = Food(keyName: "PAPAYA", months: [1, 3, 4, 8, 10, 11])
    private static let passionFruit = Food(keyName: "PASSION_FRUIT", months: [1, 11, 12])
    private static let watermelon = Food(keyName: "WATERMELON", months: [1, 11, 12])
    private static let nectarine = Food(keyName: "NECTARINE", months: [1, 3, 11, 12])
    private static let grape = Food(keyName: "GRAPE", months: [1, 2, 3, 4, 5, 10, 11, 12])
    private static let lettuce = Food(keyName: "LETTUCE", months: [1, 3, 4])
    private static let chive = Food(keyName: "CHIVE", months: [1, 10, 11, 12])
    private static let cabbage = Food(keyName: "CABBAGE", months: [1, 7, 8, 9, 10])
    private static let parsley = Food(keyName: "PARSLEY", months: [1, 3, 7, 12])
    private static let pumpkin = Food(keyName: "PUMPKIN", months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    private static let zucchini = Food(keyName: "ZUCCHINI", months: [1, 3, 5, 8])
    private static let beet = Food(keyName: "BEET", months: [1, 3, 4, 5, 10, 11, 12])
    private static let cucumber = Food(keyName: "CUCUMBER", months: [1, 2, 3, 4, 7, 10, 11, 12])
    private static let pepper = Food(keyName: "PEPPER", months: [1, 2, 8, 9, 10, 11, 12])
    private static let okra = Food(keyName: "OKRA", months: [1, 2, 3])
    private static let tomato = Food(keyName: "TOMATO", months: [1, 2, 3, 4, 10, 11, 12])
    private static let avocado = Food(keyName: "AVOCADO", months: [2, 3, 4, 5])
    private static let plum = Food(keyName: "PLUM", months: [2, 3, 4, 12])
    private static let guava = Food(keyName: "GUAVA", months: [2, 3])
    private static let jaca = Food(keyName: "JACA", months: [2, 3, 4, 5, 6])
    private static let apple = Food(keyName: "APPLE", months: [2, 3, 4, 5, 8, 9, 10, 11, 12])
    private static let pear = Food(keyName: "PEAR", months: [2, 3, 4, 5])
    private static let peach = Food(keyName: "PEACH", months: [2, 3, 11, 12])
    private static let seriguela = Food(keyName: "SERIGUELA", months: [2, 3])
    private static let escarole = Food(keyName: "ESCAROLE", months: [2, 3, 4, 8])
    private static let mint = Food(keyName: "MINT", months: [2, 10, 12])
    private static let ginger = Food(keyName: "GINGER", months: [2, 3, 4, 6])
    private static let greenCorn = Food(keyName: "GREEN_CORN", months: [2, 3, 6, 7])
    private static let bananaApple = Food(keyName: "BANANA_APPLE", months: [3, 4, 5])
    private static let bananaNanica = Food(keyName: "BANANA_NANICA", months: [3, 8, 9, 10, 11])
    private static let lemon = Food(keyName: "LEMON", months: [3, 12])
    private static let mangosteen = Food(keyName: "MANGOSTEEN", months: [3, 6])
    private static let tangerine = Food(keyName: "TANGERINE", months: [3, 4, 5, 6, 7, 8, 9, 10, 11])
    private static let chard = Food(keyName: "CHARD", months: [3])
    private static let leek = Food(keyName: "LEEK", months: [3, 4, 5, 6, 7, 8, 9, 10, 11])
    private static let coriander = Food(keyName: "CORIANDER", months: [3, 7, 8, 10])
    private static let endive = Food(keyName: "ENDIVE", months: [3, 11, 12])
    private static let arugula = Food(keyName: "ARUGULA", months: [3, 8, 12])
    private static let eggplant = Food(keyName: "EGGPLANT", months: [3, 4, 5, 6, 10, 11])
    private static let cara = Food(keyName: "CARA", months: [3, 4, 5, 6, 7, 8, 9])
    private static let chuchu = Food(keyName: "CHUCHU", months: [3, 4, 5])
    private static let yam = Food(keyName: "YAM", months: [3, 4, 5, 6, 7, 8, 9, 10, 11])
    private static let jelly = Food(keyName: "JELLY", months: [3])
    private static let turnip = Food(keyName: "TURNIP", months: [3, 4, 5, 7, 8, 11])
    private static let khaki = Food(keyName: "KHAKI", months: [4, 5])
    private static let cider = Food(keyName: "CIDER", months: [4])
    private static let kiwi = Food(keyName: "KIWI", months: [4, 5, 6, 7, 8, 12])
    private static let willReach = Food(keyName: "WILL_REACH", months: [4, 5, 6, 9, 10, 11, 12])
    private static let catalan = Food(keyName: "CATALAN", months: [4, 10])
    private static let fennel = Food(keyName: "FENNEL", months: [5, 6, 7, 8, 9, 10, 11, 12])
    private static let bay = Food(keyName: "BAY", months: [5, 9])
    private static let sweetPotato = Food(keyName: "SWEET_POTATO", months: [5, 6, 7, 10])
    private static let carrot = Food(keyName: "CARROT", months: [5, 6, 7, 8, 9, 10, 11, 12])
    private static let manioc = Food(keyName: "MANIOC", months: [5, 6, 7, 8])
    private static let littleManioc = Food(keyName: "LITTLE_MANIOC", months: [5, 6, 7, 8])
    private static let radish = Food(keyName: "RADISH", months: [5, 7, 8, 9, 10])
    private static let quince = Food(keyName: "QUINCE", months: [6])
    private static let cress = Food(keyName: "CRESS", months: [6, 7, 8])
    private static let broccoli = Food(keyName: "BROCCOLI", months: [6, 8, 9, 10, 11])
    private static let pea = Food(keyName: "PEA", months: [6, 7, 8, 9, 10])
    private static let palmHeart = Food(keyName: "PALM_HEART", months: [6, 7])
    private static let chicory = Food(keyName: "CHICORY", months: [7, 8, 9, 10])
    private static let spinach = Food(keyName: "SPINACH", months: [7, 8, 9, 10, 11])
    private static let mustard = Food(keyName: "MUSTARD", months: [7, 8, 10])
    private static let celery = Food(keyName: "CELERY", months: [7, 12])
    private static let mushroom = Food(keyName: "MUSHROOM", months: [7, 9, 10, 12])
    private static let cashew = Food(keyName: "CASHEW", months: [8, 9, 10, 11])
    private static let lime = Food(keyName: "LIME", months: [8, 10])
    private static let strawberry = Food(keyName: "STRAWBERRY", months: [8])
    private static let cauliflower = Food(keyName: "CAULIFLOWER", months: [8, 9, 10])
    private static let fava = Food(keyName: "FAVA", months: [8, 9, 10])
    private static let jaboticaba = Food(keyName: "JABOTICABA", months: [9, 10])
    private static let medlar = Food(keyName: "MEDLAR", months: [9, 10])
    private static let tamarind = Food(keyName: "TAMARIND", months: [9])
    private static let oregano = Food(keyName: "OREGANO", months: [9, 10, 12])
    private static let acerola = Food(keyName: "ACEROLA", months: [10, 11])
    private static let silverBanana = Food(keyName: "SILVER_BANANA", months: [10, 11, 12])
    private static let mango = Food(keyName: "MANGO", months: [10, 11, 12])
    private static let grapeLeaf = Food(keyName: "GRAPE_LEAF", months: [10, 11, 12])
    private static let artichoke = Food(keyName: "ARTICHOKE", months: [10])
    private static let asparagus = Food(keyName: "ASPARAGUS", months: [10, 11])
    private static let khakiTomato = Food(keyName: "KHAKI_TOMATO", months: [10])
    private static let melon = Food(keyName: "MELON", months: [11, 12])
    private static let maxixe = Food(keyName: "MAXIXE", months: [11])
    private static let cherry = Food(keyName: "CHERRY", months: [12])
    private static let damascus = Food(keyName: "DAMASCUS", months: [12])
    private static let graviola = Food(keyName: "GRAVIOLA", months: [12])
    private static let litchi = Food(keyName: "LITCHI", months: [12])
    private static let pomegranate = Food(keyName: "POMEGRANATE", months: [12])
    private static let podNoodles = Food(keyName: "POD_NOODLES", months: [12])

    static let allFoods = [
        pineapple, starFruit, greenCoconut, fig, raspberry, custardApple, orangePear, papaya, passionFruit, watermelon,
        nectarine, grape, lettuce, chive, cabbage, parsley, pumpkin, zucchini, beet, cucumber, pepper, okra, tomato,
        avocado, plum, guava, jaca, apple, pear, peach, seriguela, escarole, mint, ginger, greenCorn, bananaApple,
        bananaNanica, lemon, mangosteen, tangerine, chard, leek, coriander, endive, arugula, eggplant, cara, chuchu,
        yam, jelly, turnip, khaki, cider, kiwi, willReach, catalan, fennel, bay, sweetPotato, carrot, manioc,
        littleManioc, radish, quince, cress, broccoli, pea, palmHeart, chicory, spinach, mustard, celery, mushroom,
        cashew, lime, strawberry, cauliflower, fava, jaboticaba, medlar, tamarind, oregano, acerola, silverBanana,
        mango, grapeLeaf, artichoke, asparagus, khakiTomato, melon, maxixe, cherry, damascus, graviola, litchi,
        pomegranate, podNoodles]
}
